#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/TOF/isp_180degrFOV_TOFsensor.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -i -l -O --log outline distiller --regression element -- TEST/LARGE-tests/TOF/isp_180degrFOV_TOFsensor.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log outline resolver --regression element -- TEST/LARGE-tests/TOF/isp_180degrFOV_TOFsensor.spin2)
