#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l   --log resolver parser --regression element -v TEST/DAT-PASM-tests/flash_loader.spin2)
