#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l -O --log  resolver elementizer --regression element -v TEST/DBG-tests/debug_test_001.spin2)
