#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l --pass con-block  --log resolver parser --regression element -v TEST/DAT_COMPILE/blink_pasm.spin2)
