#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -U CLOCK_200MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -D CLOCK_300MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
