#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -c -v -l   --log resolver parser --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)
