#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l -O -B  --log compiler resolver parser --regression element -v TEST/OBJ-tests/spin_test10.spin2)
