#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l   --log resolver parser --regression element -v TEST/DAT-PASM-tests/HDMI_Spiral_Demo_800_x_480.spin2)
