#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l   --log compiler resolver parser --regression element -v TEST/SPIN-tests/spin_test3.spin2)
