#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  -i --log outline elementizer --regression element -v TEST/EXT-tests/Spin2_interpreter.spin2)
