#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -U USE_PSRAM16 -D USE_PSRAM4 --regression preproc --log preproc  -v TEST/PREPROC-tests/condNestCodeCmdLn.spin2)
