#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v  -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/PnlLtMeas/isp_measure_panel.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v  -l -O --log outline --regression element -- TEST/LARGE-tests/PnlLtMeas/isp_measure_panel.spin2)
