#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l --log resolver parser --regression element -v TEST/CON-tests/Snippet_002.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -D CLOCK_200MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCode.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -D CLOCK_300MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCode.spin2)
