#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l   --log resolver parser elements --regression element -v TEST/DAT_COMPILE/spin2_interpreter.spin2)
