#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O   --log compiler resolver parser --regression element -v TEST/LOADER-tests/blink_single.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log compiler resolver parser --regression element -v TEST/LOADER-tests/blink_single.spin2)
