#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCode.spin2)
