#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js --regression element --log parser elements -v TEST/parser_test_no_float.spin2)
