#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -d -v -l -O   --log compiler resolver parser --regression element -v TEST/LANG-VER-tests/math_128.spin2)
