#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -d -v -l -O   --log compiler resolver elementizer parser --regression element -v TEST/LANG-VER-tests/Spin2_v51_misc.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -d -v -l -O   --log compiler resolver parser --regression element -v TEST/LANG-VER-tests/Spin2_v51_misc.spin2)
