#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js --regression element --log elements resolver  -v TEST/parser_test_full.spin2)
