#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -c -v -f -l -O -B  --log compiler resolver parser --regression element -v TEST/OBJ-tests/spin_test18.spin2)
