#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log outline --regression element -- TEST/LARGE-tests/demo_hub75_7seg.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O  --regression element -- TEST/LARGE-tests/demo_hub75_7seg.spin2)
