#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/HUB75/isp_hub75_scrollingText.spin2)
