#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/flash_fs_demo.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l -O --log outline --regression element -- TEST/LARGE-tests/flash_fs_demo.spin2)
