#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l -O --log resolver --regression element -- TEST/LARGE-tests/Flash-FS/flash_fs.spin2)
