#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c --pass elementize --regression element --log parser elements resolver  -v TEST/SHORT/elementizerTESTs/parser_test_full.spin2)
