#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -d -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/iOTgw/demo_p2gw_email.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -d -O --log outline --regression element -- TEST/LARGE-tests/iOTgw/demo_p2gw_email.spin2)
