#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
#(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -U CLOCK_200MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -D CLOCK_300MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCodeElse.spin2)
