#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -v -l --log resolver parser --regression element -v TEST/RESOLVER/Snippet_001.spin2)
#(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -D CLOCK_200MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCode.spin2)
#(set -x;npm run compile && ./scripts/doit ./dist/pnut-ts.js -c -D CLOCK_300MHZ --regression preproc --log preproc  -v TEST/FULL/preprocessTESTs/condCode.spin2)
