#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -c -v -f -l -O -B  --log compiler resolver parser --regression element -v TEST/LOADER-tests/isp_dummy_flash_rpi.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -f -l -O --log compiler resolver parser --regression element -v TEST/LOADER-tests/isp_dummy_flash_rpi.spin2)
