#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l --log compiler resolver parser --regression element -v TEST/EXCEPT-tests/excpt_test_001.spin2)
