#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -f -l -O   --log compiler resolver parser --regression element -v TEST/OBJ-tests/spin_test13.spin2)
