#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -44 -l -O --log compiler resolver parser --regression element -v TEST/COV-tests/coverage_003_v44.spin2)
