#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l --log compiler resolver parser --regression element -v TEST/OBJ-tests/spin_test11_child.spin2)
